mozci/push.py
mozci/queries/push_tasks_from_unittest.query
mozci/task.py

I was unable to test this normally, as in all pushes I tried to analyze, most tasks were skipped because of missing fields.

Store unittest result, test and manifest as part of test tasks

---

mozci/push.py
mozci/queries/push_tasks_from_treeherder.query
mozci/queries/push_tasks_groups_from_unittest.query
mozci/queries/push_tasks_results_from_unittest.query

This considerably reduces the amount of data we have to pull from ActiveData.

Retrieve groups from the unittest table with a separate query, to get them only once per task

---

mozci/push.py
mozci/queries/push_tasks_from_treeherder.query
mozci/task.py
tests/test_push.py

Fixes #2
A nice example to test this on is ee582f48caa16183f496f63dfd85eefb288ba4fb, you can see the difference before/after.

Use 'fixed by commit' and back-out information to correctly attribute some regressions

---

mozci/task.py

As in https://github.com/klahnakoski/ActiveData-ETL/blob/61a5a14deafc8babac37b2bc2d67c6bcc706e65a/activedata_etl/transforms/unittest_logs_to_sink.py#L228.

Skip 'default' group just like ActiveData does

---

mozci/task.py

Since https://bugzilla.mozilla.org/show_bug.cgi?id=1614640 has been fixed.

Stop asserting crashtest and geckoview-reftest tasks have no groups

---

README.md
tests/test_integration.py
tox.ini

Stop running the integration tests as part of the default test set

---

mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_hgmo.py
tests/test_push.py

The motivation here is to enforce more guarantees on the `rev` and `revs` properties. That it is the long form in the former, and that it exists at all in the latter.
This could potentially slow down performance, as it means we query `json-automationrelevance` in the `Push` constructor. I plan on using this fact to detect non-existent pushes early in a follow-up PR.
I theorize that we pretty much always need to query `json-automationrelevance` anyway, so my hope is that the overall perf impact is minimal.

Handle `Push.rev` and `Push.revs` consistently

---

mozci/errors.py
mozci/task.py
mozci/util/hgmo.py
mozci/util/taskcluster.py
tests/test_push.py
tests/test_task.py

Currently we don't do any exception handling, resulting in a mixture of confusing `KeyError`s and `requests.HTTPError`s being raised to the user.
We should catch these and re-raise them with Python 3's `raise from` syntax:
```
try:
self._hgmo.get('rev')
except requests.HTTPError as e:
if e.response.status_code == 404:
raise PushNotFoundException from e
raise
```

Raise custom exceptions for common failure cases

---

mozci/push.py
mozci/task.py
mozci/util/hgmo.py
mozci/util/req.py
mozci/util/taskcluster.py

How do we know that it is working as expected?
On another note, look at [the second commit](https://github.com/mozilla/mozci/commit/5b1c326bbaa4c8793f4f5d6b3bcc32c2532bd045) and the output below.
I moved `@lru_cache` to the lower level function since it did not like using lru_cache as part of a function of a class.
```python
def test_missing_artifacts(responses, create_task):
artifact = "public/artifact.txt"
task = create_task(label="foobar")
responses.add(
responses.GET, get_artifact_url(task.id, artifact), status=404,
)
responses.add(
responses.GET,
get_artifact_url(task.id, artifact, old_deployment=True),
status=404,
)
with pytest.raises(ArtifactNotFound):
>           task.get_artifact(artifact)
E           TypeError: unhashable type: 'Task'
tests/test_task.py:40: TypeError …
```

Switch from memoize to lru_cache

---

mozci/push.py
tests/conftest.py
tests/test_push.py

Stop looking for failures in children pushes after we hit a backout of the push

---

mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_hgmo.py
tests/test_push.py

In particular, ignore classifications which are clearly wrong.
Fixes #118

Improve the way we handle 'fixed by commit' classifications

---

mozci/util/hgmo.py

This way we don't create two different instances when calling the function
once with a long changeset and once with its short version.

Use short changeset for caching HGMO instances

---

mozci/push.py

Other than a cleanup, this has a benefit: if we have a failure on a push with 'fixed by commit' info we add it to the list of regressions of the current push even if it was intermittent in the parent (given that we won't consider it a "prior regression")

Simplify get_regressions by having a single 'count' variable

---

mozci/push.py
tests/conftest.py
tests/test_push.py

To avoid dependencies between them, and factor out the duplicated code to iterate children.

Refactor bustage_fixed_by and get_candidate_regressions

---

mozci/errors.py
mozci/push.py
mozci/task.py
mozci/util/taskcluster.py
tests/test_push.py
tests/test_task.py

Implements ``Push.generate_all_shadow_scheduler_tasks()``.

Add an API to generate all shadow scheduler results

---

tests/test_integration.py

When running pytest against the integration we need to set ADR_CONFIG as a variable.
tox was setting the ADR_CONFIG variable, however, this would not help if we are running pytest directly. This change configures pytest with the variable.

Raise exception if ADR_CONFIG_PATH env variable is not set for integration tests

---

tests/test_integration.py

[EDIT] It's working now!
---
It's currently broken because ActiveData queries are currently broken. See https://activedata.allizom.org/tools/query.html#query_id=Lnj_Yd58, or:
```
{
"from":"treeherder",
"where":{"not":{"prefix":{"job.type.name":"Action"}}}
}
```

Add a basic integration test to make sure everything runs without exceptions

---

mozci/push.py
mozci/task.py

Fixes #171
This also gets rid of the `_groups` property (making `groups` use `_results`), since it's redundant with `_results`.

Consider groups for which we have no `test_result` line in the errorsummary to be passing

---

mozci/push.py
mozci/task.py
tests/test_task.py

Fixes #162
Example output for `Push("a2bff0eef797dc2f2f40779eb08ccfae0ceeb27f").get_regressions("group_config")`:
```
{
('windows7-32', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('macosx1014-64', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('linux1804-64-shippable', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('linux1804-64-qr', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('macosx1014-64-shippable', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('windows10-64', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('linux1804-64', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('windows10-64-shippable', 'extensions/permissions/test/unit/xpcshell.ini'): 0,
('windows10-64-shippable', …
```

Support getting regressions for groups at given configurations

---

mozci/push.py
mozci/task.py
tests/config.toml
tests/test_integration.py

Fixes #158
The original code to cache tasks was storing each task in a different cache key, which
makes the number of elements in the cache explode. We should instead cache all the tasks
of a push together.

Cache tasks' errors/results grouped as a push

---

mozci/task.py

Make sure that we don't try to load errorssummary.log for suites which don't support groups

---

mozci/task.py

Some wpt errorsummary.log files (at least some old ones, hopefully not anymore now) have 'default' as a group in the `test_result` lines.

Don't add 'default' groups to the results

---

mozci/task.py

E.g. Kh39_mBqRXO8bxTJJADYHg (test-linux1804-64-shippable-qr/opt-crashtest-e10s): [crashtest_errorsummary.log](https://github.com/mozilla/mozci/files/4643714/crashtest_errorsummary.log).

Don't fail when an errorsummary.log doesn't contain a 'test_groups' action

---

mozci/task.py

Otherwise, test-verify tasks would be considered as a different configuration.

Add test-verify to the list of suites

---

mozci/queries/push_tasks_results_from_unittest.query

Use result.ok_intermittent instead of result.ok to ignore known intermittent failures

---

mozci/push.py

Since 846798e5b9db6e3a33dd58ba0b14d19b8585f5a1, there might be cases where we have _result_group and no _result_ok
(since the ok_intermittent value is not available yet in all unittest results).

Make sure to always remove _result_group when normalizing task objects

---

mozci/push.py

There are be cases where we have _result_ok and no _result_group, e.g. Talos
Fixes a regression from ab5fe1325ad5045d738c698e276b6283dc037f4b

Make sure to always remove _result_ok when normalizing task objects

---

mozci/push.py
tests/conftest.py

Since tasks with the same name on different pushes might contain totally different tests, our algorithm at the label-level would be totally broken.

Don't consider manifest-level pushes for finding label-level regressions

---

.pre-commit-config.yaml

This change will silently incorporate the modifications that black / isort make into the commit (rather than failing and then requiring that the commit be re-run).
The author of pre-commit refuses to implement this and advises against doing this, as it means that what you have in your working directory isn't what ends up in the commit. While I do sympathize with this to some degree, in our case I found that 100% of the time was running:
```
$ git commit -a --amend
$ git commit -a --amend
```
Now the first `git commit -a --amend` will pass.

Allow commits to continue after black / isort make modifications

---

mozci/push.py

We were only ignoring the failure on the backout if it was classified as 'intermittent', but it can also be classified 'expected fail'.
For example browser/components/urlbar/tests/browser/browser.ini is failing on f00da8ba616069eae4e702bc92c44b068097519e and it is failing on its backout 2ba712ae046e081087c304c6a8a421f2ce6bceed, but the failure on the backout is marked as `expected fail`. Before this patch, we were not considering browser/components/urlbar/tests/browser/browser.ini as a regression.

Remove a regression from the list only if it was not classified or classified as failing

---

mozci/push.py
mozci/queries/push_tasks_tags_from_task.query

When manifest-level scheduling is enabled, we will still have some suites that are not chunked in the taskgraph (e.g. GTest).
We still need to be able to train the ML model on those suites, so we can't fully skip pushes where manifest-level scheduling
is enabled.
Fixes #245

Only skip tasks which are chunked in the taskgraph when looking for regressions in pushes where manifest-level scheduling is enabled

---

mozci/push.py
tests/test_regressions.py

Given that we have recently moved the backstop to be once every 20 pushes (https://hg.mozilla.org/mozilla-central/rev/17a6cf8777b1), we can't keep looking only in the previous/next 14 pushes.
Fixes #8
31 is a relatively big number, but in the end it should be fast enough when things are cached.

Make the maximum number of parents or children to look for previous/next task runs configurable

---

mozci/util/taskcluster.py
poetry.lock
pyproject.toml

To support #304.
E.g. to get all tasks belonging to a given push:
```
decision_task_id = taskcluster.find_task_id(f"gecko.v2.{branch}.revision.{rev}.taskgraph.decision")
decision_task_data = taskcluster.get_task(decision_task_id)  # could avoid this request and always assume the decision_task_id is the same as the group ID.
tasks = get_tasks_in_group(decision_task_data["taskGroupId"])
```

Add some additional methods to the taskcluster module

---

mozci/data/base.py
mozci/data/sources/treeherder/__init__.py
mozci/errors.py
tests/test_data.py

This adds some custom exceptions for various problems in the data
handler. It will also gracefully try to use the next source in line if
ContractNotFilled was raised.

Improve error handling in data handler / sources

---

mozci/push.py

Fix Push.bustage_fixed_by when there are no child pushes

---

mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_hgmo.py
tests/test_push.py

Instead of relying on both json-rev and json-automationrelevance.
Fixes #331
This depends on adding `backedoutby` information in json-automationrelevance.

Use json-automationrelevance to retrieve all information about commits

---

mozci/push.py
mozci/util/hgmo.py
tests/test_hgmo.py

The behavior of json-rev and json-automationrelevance are a bit different for non backed-out commits.
The first always has a 'backedoutby' field, and it is empty in case of non backed-out commits.
The second doesn't have a 'backedoutby' field for non backed-out commits.
Fixes #342

Assume a commit was not backed-out if the 'backedoutby' field is not present in json-automationrelevance

---

mozci/data/sources/activedata/__init__.py

Replace `bustage` with `busted` in the map to translate ActiveData results

---

mozci/data/sources/treeherder/__init__.py
mozci/task.py

This adds `push_test_groups` contract support to the Treeherder Datasource.  It also fixes a couple things that were broken with the recent changes.  When a task is in-progress, it has a result of `unknown`.  And we get the result of `busted` rather than `bustage` in our Tasks.

Treeherder datasource push test groups

---

mozci/task.py

It is only used once, there is no need to memoize it.

Don't memoize the Task artifacts property

---

.isort.cfg
mozci/data/base.py
mozci/data/contract.py
poetry.lock
pyproject.toml
tests/test_data.py

ValidX claims to be 3x faster than voluptuous on average. While this likely won't make a big difference, the change is simple plus errors seem to be much nicer. I also wanted to explore this library for use in the taskgraph.

Replace voluptuous with validx for schema validation

---

mozci/data/sources/artifact/__init__.py

This can happen if the task hasn't been scheduled yet. I decided to
return an empty dict rather than raise ContractNotFilled since this
should typically be the last data source in the list and we likely don't
want to raise every time a task is still running / pending.

Return an empty dict if no errorsummary loaded in ErrorsummarySource

---

mozci/push.py
mozci/task.py
tests/test_task.py

The task.results attribute expects the _results property to have a value.
Since e488ccd4966163ed9532ab51f4584fc60286ae10, we don't populate _results
at the time of task creation for incomplete tasks (e.g. tasks ending with
'exception'). Later on, we try to access the task.results attribute for all
tasks, even incomplete ones, and so the assertion on _results not being None
fails.
Fixes #473, a regression from e488ccd4966163ed9532ab51f4584fc60286ae10

Set incomplete task results to an empty list

---

mozci/push.py
mozci/task.py
test.py
tests/test_push.py
tests/test_task.py

Closes #504 
Algorithm implemented in `classify_regressions` for a push  is :
1. get schedules from bugbug (or local cache)
2. get likely regressions from mozci  (or local cache)
3. sort bugbug groups into high & low confidence buckets (excluding the medium ones)
4. detect if likely regressions is a cross config failure or not
5. get all groups that fail
6. build the group lists:
- real failures = `likely_regressions & groups_cross_config_failure & groups_high`
- intermittent failures = `groups_non_cross_config_failure & groups_low`
- unknown failures = remaining failures not in the two previous lists
A second method `classify` simply gets those list and extrapolates a single value for the whole push:
- `PushStatus.BAD` when there are real failures 
- `PushStatus.GOOD` when there are only …

Classify regressions and push using bugbug data

---

mozci/console/commands/push.py

Add an option on the classify command to print intermittent tasks

---

.taskcluster.yml
Dockerfile
pyproject.toml

Closes #545 & #539 
The image is built using [mozilla/task-boot](https://github.com/mozilla/task-boot/) + Taskcluster dind.
It's currently available as a Taskcluster artifact. We now have 2 choices for further publication:
1. only publish as artifact, and index the task so that other Taskcluster task (on the same instance) can use that image
2. add Docker hub credentials in a secret, and use it through `task-boot push-artifact` in order to publish the image on Dockerhub.
We also need to define a publication strategy:
- push as `latest` on `master` (merges) ?
- push as `X.Y.Z` on tags `X.Y.Z` (releases) ?
- push on specific production or other branches ?

Add docker image based on alpine

---

.taskcluster.yml

Port from [code-review definition](https://github.com/mozilla/code-review/blob/master/.taskcluster.yml#L13-L15).
The merged branches are not indexed by their branch name because Taskcluster/Github use a `refs/heads/xxx` structure for its git references: this gives `index.project.mozci.docker.branch.refs/heads/master` for `master` which is invalid.

Strip refs/heads/ from Taskcluster branch index

---

mozci/console/commands/decision.py

This fixes the route syntax to really index the children tasks, and match the [scopes available to the hook](https://github.com/mozilla/community-tc-config/blob/main/config/projects/mozci.yml#L58)

Fix index route in decision children tasks

---

mozci/console/commands/push.py
mozci/task.py
mozci/util/taskcluster.py

As we can't retrieve classification results from artifacts for now, the command only displays pushes that were backed-out or not.
Closes #553

Add a new Cleo command to compare classification results with reality

---

mozci/configuration.py
mozci/console/commands/decision.py
mozci/util/cache_stores.py
mozci/util/taskcluster.py

Closes #572 & #564 
A few things are happening here:
1. a docker-worker cache is enabled for children tasks (see scope request https://github.com/mozilla/community-tc-config/pull/455 )
2.  in order to use that cache, we need to configure mozci in Taskcluster. The best way to do that is to use a Taskcluster secret
3. so the `Configuration` class uses an optional environment variable `TASKCLUSTER_CONFIG_SECRET` that is also set on the children tasks (the decision task does not need configuration).
4. then it's fairly immediate: any child task will use that configuration and merge it as it would from a file. So if we set the correct configuration in `project/mozci/testing` the shared cache will be used
Maybe we should add some debugging output regarding the cache configuration to make sure …

Use Taskcluster secret as configuration source to use cache

---

mozci/console/commands/decision.py

mozci classification tasks are currently failing due to a missing scope to attach the cache ([example](https://community-tc.services.mozilla.com/tasks/dpW2t0hFT42fMPSb-qTfOg/runs/0/logs/public/logs/live.log)).
This MR simply adds the relevant scope that is set on the [hook role](https://community-tc.services.mozilla.com/auth/roles/hook-id%3Aproject-mozci%2Fdecision-task-testing). I thought this scope would be validated on task creation

Explicit scope attribution for the cache

---

mozci/console/commands/decision.py

Classification tasks are starting again but failing to fetch the requested secrets as they reach the TC instance through the external interface, and not the proxy.
Example : https://community-tc.services.mozilla.com/tasks/ZCjT6bAJSl6azfaBd4HAqg/runs/0/logs/public/logs/live.log

Enable Taskcluster proxy on classifications tasks

---

mozci/push.py
tests/test_push.py

While working on the groups CSV output that Bastien asked for [here](https://github.com/mozilla/mozci/issues/563#issuecomment-990738797), I might have found a fix for the empty lists of tasks associated with some intermittent groups.
Turns out, we were using groups marked as PASSING as well as the ones marked as FAILING in `groups_cross_config_failure` and `groups_non_cross_config_failure`.
By looking at the logs from the `classify` command (tested on push `mozilla-central/4185629111d323484d1f74a667d57145616203b7`), we can see that with the previous implementation we had a lot more of intermittent groups than failing ones:
```
11:33:36.890 | DEBUG    |      mozci.push:1033 - Got 91 groups with high confidence
11:33:36.891 | DEBUG    |      mozci.push:1034 - Got 734 groups with low …
```

Fix intermittent groups having an empty list of tasks associated to them

---

mozci/console/commands/push.py

- Add more logging:
- around errors
- on recalculate normal flow
- on Taskcluster task fetch normal flow
- Refactor the output & inner triage of push classification so it can generate both:
- same summary output
- a CSV output with more detailed informations (tracking exceptions)

Enhance command push classify-eval

---

mozci/console/commands/push.py
mozci/data/contract.py
mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_push.py
tests/test_regressions.py

The classification algorithm uses the method `Push.bustage_fixed_by` that trigger an HGMO query for each push, just to get their related Bugzilla bug ID.
This patch uses the `full=1` parameter on HGMO json-pushes method in order to get the description of each revision, and thus their Bugzilla bug ID.
Here is a benchmark running on a random recent autoland revision (command `time mozci push classify-eval --rev=808ac93bdd9847272087ba981173bc877cff0425 --recalculate`)
|            | master    | parse-bug-description |
|------------|-----------|-----------------------|
| cold cache | 1m35,881s | 0m8,662s              |
| warm cache | 0m15,875s | 0m6,002s              |
On another revision which triggers good `time mozci push classify-eval --rev=9c1b66dcaac38344a227cc6cdf3e29272b487c98 …

Speedup classification by avoiding to load each push information

---

mozci/push.py
mozci/task.py
tests/test_task.py

The original logic @La0 wrote in #526 was correct, my review comment (https://github.com/mozilla/mozci/pull/526#pullrequestreview-787961109) to change it was wrong.

Fix the cross config logic to consider failures as cross config when they happen on all configurations

---

mozci/push.py

When trying to identify backout pushes, don't fail if a child push does not exist yet

---

mozci/configuration.py

This is the more commonly used syntax, and already setup on the monitoring hook

Support TASKCLUSTER_SECRET env variable too

---

mozci/console/commands/decision.py
mozci/data/sources/taskcluster/__init__.py

This should fix the auth error we are seeing on [current tasks](https://community-tc.services.mozilla.com/tasks/XmPemN9jSLSs4YGltugLhg/runs/0/logs/public/logs/live.log)
And also allow the children task to actually send emails (once https://github.com/mozilla/community-tc-config/pull/464 is applied)

Fix email scopes

---

mozci/console/commands/push.py

Fixes #606
This is a bit of a hack, but adding an option for it all over the place that is only used during evaluation seemed a bit overkill.

Pretend there were no manual classifications when evaluating the autoclassification results

---

mozci/console/commands/decision.py
mozci/console/commands/push.py
mozci/data/contract.py
mozci/data/sources/taskcluster/__init__.py
mozci/push.py

This generalize the existing code to support various Taskcluster environments.
We would have:
- `testing` running as currently, except all classification tasks routes are prefixed with `testing` 
- `production` would need to be created and will run a dedicated branch build (named `production`).
Current classifications tasks would be promoted to production, so we have the longest history possible

Support environment option

---

mozci/console/commands/decision.py
mozci/console/commands/push.py
mozci/util/taskcluster.py

While fixing current issues on prod environment (https://github.com/mozilla/community-tc-config/pull/466) I noticed that the `classify-eval` was always using production index for existing pushes.
I also added the environment in the email subject.

Support environment in classify-eval

---

mozci/push.py
tests/test_push.py

To identify real failures, we check that at least three tasks on any configuration are exhibiting the failure.
To identify intermittent failures, we check that there are no configurations with two tasks exhibiting the failure.
The numbers are configurable through the parameters to the push classify function.
Fixes #607

Add an option to take into account failures happening consistently on a given configuration when classifying pushes

---

mozci/console/commands/push.py
mozci/push.py
mozci/task.py
tests/test_push.py
tests/test_task.py

Fixes #534 
Assumption:
- `regressions.unknown` returns a map of the manifest name mapped to a list of unknown tasks within that manifest.

Extend the classify command to perform retriggers on unknown tasks (Fixes #534)

---

mozci/push.py
mozci/task.py
tests/test_push.py
tests/test_task.py

The option can be None if we want to disable cross-config detection, or a tuple with two ints where:
- the first number specifies the number of configurations to consider a failure as cross-config for intermittent detection;
- the second number specifies the number of configurations to consider a failure as cross-config for real failure detection.
This way we can tune the detection. E.g. if we want to be conservative, we can set a low first number and a high second number.
Fixes #605

Add an option to define the minimum number of configurations to consider a failure as cross-config

---

mozci/push.py
tests/test_push.py

A failure is intermittent when it is not cross-config *and* not config-consistent, we were instead
checking if it was either not cross-config or not config-consistent.

Fix intermittent detection logic

---

mozci/push.py
tests/test_push.py

Take into account group results in following pushes too for determining cross config failures

---

mozci/console/commands/decision.py
mozci/console/commands/push.py

Closes #616 
@marco-c Do you think we need a new PR on the **community-tc-config** repo to add the `on-failed` route to the [Decision task `grant` list](https://github.com/mozilla/community-tc-config/blob/main/config/projects/mozci.yml#L56)?
If so, should we send mails for production/testing fails or just for production ones?

Don't eat errors during push classification + Notify by email on TC task failure

---

mozci/util/taskcluster.py
tests/test_notify.py

Use m.text msgtype instead of default m.notice one for Matrix notification

---

mozci/console/commands/push.py

Tasks that didn't fail clearly don't have a classification. This was causing us to find
a lot of conflicting classifications just because of group failures that were happening
on a subset of configurations.
Fixes #675

Don't use classifications from tasks that didn't fail when comparing classifications

---

docs/configuration.rst
mozci/configuration.py
mozci/console/commands/push.py
mozci/task.py
tests/test_task.py

Refs #665 
This extends the mozci configuration to support autoclassification parameters to enable/disable the feature globally, and filter out which test will be enabled.
```toml
[mozci.autoclassification]
enabled = true
test-suite-names = ["test-linux64*/opt-mochitest-*"]
```
The filter support [fnmatch](https://docs.python.org/3/library/fnmatch.html#fnmatch.fnmatch) syntax to allow glob-like syntax (using `*` for wildcard and `?` for single characters).
The configuration above will enable autoclassification for test matching `test-linux64*/opt-mochitest-*`
Finally, the JSON classification output is extended to have:
~~- a top level `autoclassification` boolean flag to check if the results should processed at all,~~
- an `autoclassify` boolean flag on each failure details payload, to …

Add filters to control autoclassification in JSON output from config

---

mozci/data/contract.py

Fixes #709
We already skip them, and log an error about them, in https://github.com/mozilla/mozci/blob/df413c054baba820f43ed3dc7f86be4d10826a78/mozci/task.py#L112. So, temporarily allowing empty group names to pass validation as a workaround for the problem won't have any countereffects.

Temporarily allow groups with no name

---

mozci/data/sources/taskcluster/__init__.py

The taskcluster library is failing on 303.
Fixes #737

Switch to using index.buildUrl and manual requests.get instead of relying on the taskcluster library to get the artifact

---

mozci/console/application.py
mozci/console/commands/check_backfills.py
mozci/console/commands/push.py
mozci/util/taskcluster.py

Add a new command to check backfills completion on last pushes

---

mozci/util/taskcluster.py

@marco-c Please, tell me if you prefer that I handle the issue some other way than with this `use_put` attribute.

Fix check-backfills by using PUT instead of POST to index the current task

---

mozci/util/taskcluster.py

So we can use the Taskcluster proxy easily and so we actually use the scopes we are assigned

Use taskcluster library to index check-backfill tasks

---

mozci/console/commands/check_backfills.py

- Add link to Push with 20 ancestors in the Matrix notification
- Only send the notification once for each Treeherder symbol
(even if the symbol is associated to multiple pushes)
Closes #746 
Closes #747

Improve check-backfills command

---

mozci/task.py
tests/test_task.py

Backfill with times set to 5 when a task is not classified

---

mozci/console/commands/push.py

A couple of minor improvements to the warning about backedout pushes that are never classified as cause of any failure

---

mozci/console/commands/push.py

E.g. if the group is classified as "intermittent" and then "fixed by commit"
Linked to https://github.com/mozilla/mozci/issues/739

Warn when there are inconsistent classifications for a given group

---

mozci/console/commands/push.py

Closes #780 
@marco-c You might need to add the `matrix-room-id` attribute in the `classify-eval` command secret, I don't remember if the secret is shared between all commands or if we use separate ones...

Notify the Matrix room for all warnings from #739

---

mozci/task.py
tests/test_task.py

E.g. in https://firefoxci.taskcluster-artifacts.net/BApCu7UpRmyY0FguiQcacg/0/public/test_info/xpcshell_errorsummary.log we have:
```
{"test": "browser/components/migration/tests/unit/test_MigrationUtils_timedRetry.js", "subtest": null, "group": "browser/components/migration/tests/unit/xpcshell.ini", "status": "FAIL", "expected": "PASS", "message": "xpcshell return code: 0", "stack": null, "known_intermittent": [], "action": "test_result", "line": 4866}
{"test": "browser/components/migration/tests/unit/test_MigrationUtils_timedRetry.js", "subtest": "testgetRowsFromDBWithoutLocksRetries", "group": "browser/components/migration/tests/unit/xpcshell.ini", "status": "FAIL", "expected": "PASS", "message": "[testgetRowsFromDBWithoutLocksRetries : 270] A promise chain failed to handle a rejection: …
```

Allow autoclassification when there are multiple failures of the same type reported for the same test

---

mozci/push.py
mozci/task.py
tests/test_task.py

Also refactor the failure consistency check in a separate function so it is more readable compared to an inline if.

Don't consider groups as intermittent only if they are both inconsistently failing across configs and in retriggers within the same config

---

mozci/push.py
mozci/task.py
tests/test_push.py
tests/test_task.py

Fixes #832
In practice, this means a group which is not classified as "NEW" and which is failing on a config and passing on another or failing at first and passing on a retrigger, will be autoclassified as intermittent.
Depends on #1044.

Consider groups classified as "NEW" to be potentially regressions and groups not classified as "NEW" to be potentially intermittents

---

mozci/console/commands/push.py
mozci/push.py
mozci/task.py
tests/test_push.py
tests/test_task.py

this is to show a WIP
I still need to:
* create unittests
* remove my hack for 2 days (needed that for a try push <8 hours old)
* decide on logic for how to use cf tasks

add logic to mozci for using and triggering confirm failures

---

mozci/task.py

On Android, assume suite is 'junit' when it is empty

---

.taskcluster.yml

We intend to remove support for Ubuntu 22.04, and are migrating all worker pools to Ubuntu 24.04. Let us know if that is a problem! Thanks. :-)

Migrate CI from Ubuntu 22.04 to Ubuntu 24.04

---

mozci/data/contract.py
mozci/data/sources/taskcluster/__init__.py
mozci/task.py
tests/test_data_sources.py

Part of #1145
This loads the `extra.treeherder.jobKind` from taskcluster task definition onto the `Task` class.

Store extra.treeherder.jobKind on Task

---

mozci/push.py

Mostly fixes a misleading message about "introduced" regressions when there actually are previous occurrences.

Improve logging for build regression analysis

---

mozci/data/contract.py

Currently, this aborts mozci runs:
```
ERROR    | mozci.data.base:87  - Result from contract 'push_revisions' does not conform to schema!
<SchemaError(errors=[
<0.revs.0.git_node: ForbiddenKeyError()>,
<0.revs.0.git_parents: ForbiddenKeyError()>,
``

update push_revisions scheme to include 'git_node' and 'git_parents' returned by the server

---

mozci/configuration.py
mozci/console/commands/push.py

Closes #1188
The two initial points about build failure detection seems to be covered by #1167. The detection is based on the `jobKind` attribute being `"build"`, and result being one of `{"busted", "failed", "exception"}` .

Prevent retriggering more than 15 failed build tasks
