mozci/push.py
mozci/queries/push_tasks_from_treeherder.query

When a task is re-tried, make sure only the latest run is considered

---

.gitignore
mozci/push.py
mozci/queries/push_revisions.query
mozci/queries/push_tasks_from_treeherder.query
mozci/queries/push_tasks_from_unittest.query

Changes for requesting large resultsets
Depends on https://github.com/mozilla/adr/pull/46

larger resultset

---

mozci/push.py
mozci/queries/push_tasks_from_treeherder.query
mozci/queries/push_tasks_groups_from_unittest.query

Use 'table' format when possible

---

mozci/push.py
mozci/task.py

Add alternatives to the 'regressions' functions to get group-level regressions

---

mozci/push.py
mozci/queries/push_tasks_results_from_unittest.query
mozci/task.py

Only gather information at the level of manifests

---

mozci/push.py
tests/test_push.py
tox.ini

This is also adding two basic unit tests.

When counting the distance between a push and a failure, stop at the first push with the failure

---

mozci/push.py
tests/test_push.py

Penalize candidate regressions when a push was not backed-out

---

mozci/push.py
mozci/task.py

Skip gathering groups for tasks which don't support groups yet

---

mozci/push.py

Skip empty classification notes

---

mozci/push.py
mozci/queries/push_revisions.query

Use 'format: table' for the push revisions query

---

mozci/push.py
mozci/util/hgmo.py
tests/test_hgmo.py
tests/test_push.py

Creates a new HGMO class to handle all hg.mozilla.org activities.

Refactor hg.mozilla.org url handling

---

mozci/push.py
mozci/util/hgmo.py
poetry.lock
pyproject.toml
tests/test_hgmo.py
tests/test_push.py

Refactor url and hg.mozilla.org downloading

---

mozci/util/hgmo.py
mozci/util/req.py
mozci/util/taskcluster.py
tests/test_hgmo.py

Use a single session for HGMO requests

---

mozci/push.py
tests/test_push.py

See #67
Or, we could go all the way and skip intermittents altogether (like we do when a failure is classified as 'intermittent'). WDYT @ahal?

Make intermittent failures less likely to be considered regressions

---

mozci/push.py

Retrieve groups for all tasks in a push in parallel

---

.flake8
.isort.cfg
.pre-commit-config.yaml
.travis.yml
mozci/__init__.py
mozci/push.py
mozci/task.py
mozci/util/hgmo.py
mozci/util/req.py
mozci/util/taskcluster.py
mozci/util/yaml.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_hgmo.py
tests/test_push.py
tox.ini

Use black and pre-commit

---

mozci/push.py
tests/conftest.py
tests/test_push.py

Drop regressions from pushes which were not backed out and had no bustage fix

---

mozci/push.py
mozci/task.py
tests/test_integration.py

I run the test locally with `pytest tests/test_integration.py -k test_caching_of_tasks`.
A directory `adr_cache` is created.
How can I determine if anything is being cached?

Fixes #86 - Cache task groups and results

---

mozci/util/req.py

some default values

---

mozci/task.py
tests/test_task.py

Create a Task.to_json() helper to JSONify a task instance

---

mozci/task.py
tests/integration_queries/test_all_groups.query
tests/integration_queries/test_all_result_groups.query
tests/test_integration.py

First part for #153.
Need to wait a few days before being able to update `test_missing_manifests` and `test_missing_result_manifests`, and there is some issue in ActiveData that @ekyle is looking into.

First part for supporting WPT groups

---

.gitignore
README.md

This are the changes required for windows install, and running of tests

Add troubleshooting docs for some Windows issues

---

tests/integration_queries/test_missing_result_manifests.query
tests/test_integration.py
tox.ini

Support WPT groups

---

mozci/task.py
tests/test_integration.py

Transform WPT group names to a full relative path in mozilla-central

---

mozci/push.py
mozci/util/hgmo.py
mozci/util/taskcluster.py

The main change is the fix for #189.

Some memoization improvements

---

mozci/task.py

Ignore skipped groups (from errorsummary.log)

---

mozci/task.py
tests/test_task.py

When analyzing a given group, we were considering classifications belonging to failing tasks which contained the group whether the group failed or not. If the group didn't fail, we can be sure that the classification was not related to it.

Don't consider classifications for failing tasks that contain a group, if the group didn't fail

---

mozci/push.py
mozci/task.py

Don't trust test-verify results, unless there is at least one group failure reported

---

mozci/push.py
mozci/util/hgmo.py
tests/test_hgmo.py
tests/test_regressions.py

I've identified a few improvements that could be done to the regression finding algorithm by comparing some of the regressions found so far at the label-level vs the group-level.
See #198.

Misc improvements to the regression finding algorithm

---

mozci/task.py

test-verify tasks might have multiple errorsummary.log files.

Support tasks with multiple errorsummaries

---

mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_regressions.py

I think we can consider #198 closed after this (all remaining things in that issue are tracked in other issues).

Additional misc improvements for analyzing regressions

---

mozci/push.py
tests/conftest.py
tests/test_regressions.py

Support getting data for try pushes

---

mozci/util/hgmo.py

Raise a PushNotFound exception when trying to access an invalid revision

---

mozci/push.py

Instead, return a set of tasks when a shadow scheduler did not fail, and an exception when a shadow scheduler failed.
Fixes #144

Make Push.generate_all_shadow_scheduler_tasks not throw an exception when one or more shadow schedulers failed on the push

---

mozci/push.py
mozci/task.py

Don't ignore test-verify passes in pushes which contain the fix for bug 1640758

---

mozci/push.py

So the Task's __post_init__ method has a chance to run on a complete object
Fixes #267, a regression from fdae1b03a73a9cb47900dd2cd0bedc0076742a67

Create a Task object from the task data only after the data is complete

---

mozci/data/contract.py
mozci/util/hgmo.py
mozci/util/req.py
mozci/util/taskcluster.py

Add missing allowed values to classification schema

---

mozci/push.py
mozci/task.py
tests/test_regressions.py

Don't consider intermittent failures which were already intermittent in a close parent as regressions

---

mozci/data/base.py
mozci/data/sources/treeherder/__init__.py

@ahal - Does this look about right?  Please let me know if I'm on the right track or off in the weeds...  :)

Create a Treeherder Datasource

---

mozci/push.py
tests/test_push.py

Ensure we use correct branch when calling Push.create_push()

---

mozci/util/taskcluster.py
tests/test_push.py
tests/test_task.py

xref #230
I've got fail test on flake8 when run pre-commit on my local, but no error. please tell me if I need to fix something related to this PR
cc: @marco-c

FIX: remove all code related to old_deployment

---

mozci/data/contract.py
mozci/data/sources/activedata/__init__.py
mozci/push.py

This is the first step for #301.

Make push_revisions a contract and implement it in the ActiveData data source

---

mozci/data/base.py
mozci/data/sources/hgmo/__init__.py
mozci/util/hgmo.py

Add a hg.mozilla.org-based data source to retrieve push revisions

---

mozci/data/base.py
mozci/data/contract.py
mozci/data/sources/activedata/__init__.py
mozci/data/sources/taskcluster/__init__.py
mozci/data/sources/treeherder/__init__.py
mozci/push.py

@camd unfortunately I can't properly test the changes in the treeherder data source you wrote.

Add a Taskcluster-based data source to retrieve list of tasks which ran on a given push

---

mozci/data/base.py
mozci/data/contract.py
mozci/data/sources/activedata/__init__.py
mozci/data/sources/activedata/queries/push_tasks_from_treeherder.query
mozci/data/sources/taskcluster/__init__.py
mozci/data/sources/treeherder/__init__.py
mozci/push.py
mozci/task.py
tests/test_data_sources.py
tests/test_regressions.py
tests/test_task.py

Add a treeherder_client data source to retrieve classifications using the public API

---

mozci/data/sources/taskcluster/__init__.py
tests/test_data_sources.py

Fix assumption that tasks which are 'resolved' are also 'started'

---

mozci/push.py
mozci/task.py
tests/test_push.py

Add a method to generate all groups, on given configurations, selected by shadow schedulers

---

mozci/util/cache_stores.py

Protect creation of boto s3 clients with a lock

---

mozci/data/sources/taskcluster/__init__.py

Fixes #346
My only worry is that we wouldn't easily notice if somebody changes the index path (it has happened once before).

Don't fail when hitting pushes with a broken decision task, just skip them instead

---

mozci/util/hgmo.py

Pass backouts=1 to json-automationrelevance to retrieve backedoutby information

---

mozci/data/contract.py
mozci/data/sources/treeherder/__init__.py
tests/test_data_sources.py

Support the 'push_test_groups' contract in the 'treeherder_client' data source

---

.isort.cfg
mozci/task.py
mozci/util/taskcluster.py

Don't load all errorsummary.log lines in memory

---

mozci/push.py
tests/test_integration.py

Fixes #368
Previously, we were relying on adr caching the results of AD queries, so the `data.handler.get` calls in the `tasks` function were relatively quick as they were hitting the cache.
Now, this is not happening anymore with the different data sources that we have introduced. So if we run a script which accesses `push.tasks` twice, the second will not be fast as it used to be.
Also now that the `data.handler.get` calls are not cached, we don't need to worry about storing the same data twice, and so we can cache the whole tasks list instad of only caching the errorsummary.log results ,

Cache all push tasks

---

.taskcluster.yml
.travis.yml
README.md

Switch to Taskcluster

---

mozci/data/sources/hgmo/__init__.py
mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_hgmo.py
tests/test_push.py
tests/test_regressions.py

Grab json-pushes for multiple pushes at a time when iterating over children/parents

---

mozci/data/contract.py
mozci/data/sources/artifact/__init__.py
mozci/data/sources/treeherder/__init__.py
mozci/push.py
mozci/task.py
tests/test_data_sources.py
tests/test_regressions.py

Fixes #449, a regression from d35ba97

Remove circular dependency between push and task objects

---

mozci/configuration.py
mozci/data/base.py
mozci/data/contract.py
mozci/data/sources/taskcluster/__init__.py
mozci/errors.py
mozci/push.py
tests/test_data_sources.py

Taskcluster push tasks fix

---

tests/test_data_sources.py

removed unused FakePush Class in tests/test_data_sources.py

---

docs/usage.rst

I came across this doc today and thought we should bring it up to date.

Update usage documentation

---

.isort.cfg
.pre-commit-config.yaml
mozci/console/application.py
mozci/console/commands/push.py
poetry.lock
pyproject.toml

This includes a simple 'mozci push tasks' subcommand that lists the
tasks that ran on a push along with their result.

Add a bare-bones CLI for mozci

---

mozci/console/commands/push.py

Add a Cleo command to classify a Push

---

mozci/console/commands/push.py
mozci/push.py
tests/test_push.py

Based on #538 
Closes #536
Closes #540

Allow to specify confidence thresholds and output path in classify command

---

mozci/console/commands/push.py
mozci/push.py

Support classifying a range of pushes in the classify command

---

.taskcluster.yml

Should run after https://github.com/mozilla/community-tc-config/pull/452 is merged

Switch to proj-mozci for CI

---

.taskcluster.yml
mozci/console/application.py
mozci/console/commands/decision.py
mozci/data/contract.py
mozci/data/sources/treeherder/__init__.py
mozci/push.py
mozci/util/taskcluster.py

Build simple decision task spawning child tasks on CI

---

mozci/push.py
tests/test_push.py

Add 'is_finalized' property to pushes to control caching

---

.pre-commit-config.yaml

Update pre-commit hooks & remove seed-isort-config

---

mozci/data/sources/artifact/__init__.py

Fixes  #587 
Skipped error logs for pushes on the `try` branch.

Ignore errors for `try` pushes (Fixes  #587)

---

mozci/configuration.py
mozci/push.py
tests/conftest.py
tests/test_regressions.py

Add a parameter to get regressions without assumptions about backouts

---

.gitignore
mozci/task.py
mozci/util/taskcluster.py
tests/test_task.py

Implement ability to perform retriggers on a push (Fixes #508)

---

mozci/console/commands/push.py
mozci/push.py
poetry.lock
pyproject.toml

Support monitoring mode in the classify-eval command

---

mozci/task.py
tests/test_task.py

Add a method to identify failures happening consistently on a given configuration

---

mozci/console/commands/push.py

Improve classify-eval command to support group classifications detailed comparison

---

mozci/console/commands/push.py
mozci/util/taskcluster.py
tests/test_notify.py

Send a Matrix notification when a BAD push is identified

---

mozci/console/commands/push.py

Clarify error message when there are errors fetching classifications

---

mozci/console/commands/push.py

Closes #637 
@marco-c I'm not sure I understand this part of the linked issue:
> For real failures it's a bit more difficult, because we have to get failures from following pushes too (in case a given group failed because of a push but didn't run on the push itself). We can get all failures starting from the push of interest and ending with its backout, and filter them by the "fixed by commit" note. Or more simply, we can just use get_likely_regressions with the historical_analysis parameter set to True.
Could you provide me with more details or maybe you know how to implement this logic in a simple way and could commit on top of this PR?

Expand classification comparison to failures missed by mozci

---

mozci/console/commands/push.py

Ignore classifications from parents/children during classify-eval --recalculate

---

mozci/console/commands/decision.py
mozci/util/taskcluster.py

Related to https://github.com/mozilla/community-tc-config/pull/467 for the scopes

Add Matrix scopes to child tasks + Reraise after catch on notification error

---

mozci/console/commands/push.py

Ignore retriggers/backfills when using --recalculate during classify-eval

---

mozci/util/taskcluster.py
poetry.lock
pyproject.toml
tests/test_notify.py

Format Matrix report by converting it to HTML

---

mozci/data/contract.py
mozci/data/sources/artifact/__init__.py
mozci/task.py
tests/test_data_sources.py

Identify failures type for a Push and group them by test group

---

mozci/task.py
tests/test_task.py

Include failure types filtering logic in is_autoclassifiable function

---

mozci/console/commands/push.py

Expose failing test names in classification JSON output

---

mozci/console/commands/push.py
mozci/push.py
mozci/util/hgmo.py
tests/conftest.py
tests/test_notify.py

Display Push author and partial date in classify notifications

---

tests/conftest.py

Prevent tests from failing because of create_push pytest fixture

---

mozci/console/commands/push.py

Allow to set 'classify' parameters through config in Classify and ClassifyEval commands

---

mozci/console/commands/check_backfills.py

Add the newest push child in the check-backfills notification

---

mozci/task.py
poetry.lock
pyproject.toml
tests/test_task.py

Implement ability to perform backfills on tasks

---

mozci/console/commands/push.py
mozci/push.py

Warn about pushes that are backed-out and where all failures on the push itself and its children are marked as intermittent

---

mozci/console/commands/push.py
mozci/util/hgmo.py

Warn if there is a classification that references a revision that does not exist

---

mozci/console/commands/push.py

Clearly a push that is newer than the failure can't be the cause of the failure
Linked to #739
Depends on #779

Warn when a failure is classified as fixed by a backout of a push that is newer than the failure itself

---

mozci/configuration.py
mozci/console/commands/push.py
mozci/push.py
tests/test_push.py

Closes #654 
@marco-c Please do not hesitate to let me know if there is anything I have misunderstood from the steps you specified in the issue.

Extend the classify command to perform backfills and retriggers

---

mozci/console/commands/push.py
mozci/task.py
tests/test_task.py

Using firefox-ci client we also use for backfills
Fixes #765

Implement retriggers using retrigger action

---

.taskcluster.yml

Use generic-worker instead of docker-worker for dind tasks...

Fix dind problems

---

mozci/console/application.py
mozci/console/commands/batch_execution.py
mozci/console/commands/push.py

It is currently broken since the last Cleo update.
Fixes #973

Correctly handle Cleo subcommands

---

mozci/console/commands/decision.py

Related to https://github.com/mozilla/community-tc-config/pull/646.

Add generic-worker cache scope

---

mozci/util/cache_stores.py

Avoids the deprecation of distutils
Closes #1062

Replaces distutils copy_tree with shutil version

---

mozci/data/contract.py
mozci/data/sources/taskcluster/__init__.py
mozci/push.py
mozci/task.py

Avoid retrigger a task failed with exception DEADLINE_EXCEEDED

---

mozci/task.py
tests/test_push.py

mozilla-central change in bug 1982404

update path for variants.yml about test variants

---

mozci/console/commands/push.py
mozci/task.py
tests/test_task.py

Use the right actions to retrigger tasks
